language: node_js
node_js:
  - 10
  - 9
before_install:
  - sudo apt-get install -y libxml2-dev
addons:
  apt:
    update: true
install:
  - npm install
  - cd client && npm install && cd ..
script:
  - npm run test-with-coverage
